api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import ( 
    TokenObtainPairView,
    TokenRefreshView,)

urlpatterns = [
    # Generate token on login to be stored in the browser. 
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # When the token expires, refresh and generate a new token that updates the old token. 
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>', views.getProject),
    path('projects/<str:pk>/vote/', views.projectVote),

    path('remove-tag/', views.removeTag),
]

dev-search-course/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

dev-search/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# Static helps create urls for static files. 
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="reset_password.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="reset.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"), name="password_reset_complete"),
]

# Static function creates file path where media root, then media url is where user uploaded content is sent.
# Grabs the media url and appends to media root. 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),

    path('', views.profiles, name="profiles"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),

    path('account/', views.userAccount, name="account"),
    path('edit-account/', views.editAccount, name="edit-account"),

    path('create-skill/', views.createSkill, name="create-skill"),
    path('update-skill/<str:pk>', views.updateSkill, name="update-skill"),
    path('delete-skill/<str:pk>', views.deleteSkill, name="delete-skill"),

    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>', views.viewMessage, name="message"),
    path('send-message/<str:pk>', views.createMessage, name="send-message")
]

projects/models.py
from django.db import models
from users.models import Profile
import uuid

# Create your models here.

# By default in Django, inheriting models automatically applies id. 
class Project(models.Model):
    # Projects to user is many to one relationship, use foreign key to get them to communicate with each other.
    # Won't let migration run unless have null=True.
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    # Title by default will be required. 
    title = models.CharField(max_length=200)
    # null=True means this data can be created without an initial value. 
    description = models.TextField(null=True, blank=True)
    # Django automatically picks up "default.jpg" if folder structure follows convention of static/images/file_name.
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    # Blank true means allowed to submit a form with value being empty. 
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    # With no quotations, requires function to be above, but with quotations hoists the function to the function.
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    # auto_now_add automatically generates a timestamp when created. 
    created = models.DateTimeField(auto_now_add=True)
    # Overriding default id with uuid as the new primary key.
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    # Python function to refer to Project class and return the title instead of the object uuid.
    def __str__(self):
        return self.title
    
    # Order the projects model. Adding "-" changes from ascending to descending order. 
    # Orders in order of list in ordering. 
    class Meta:
        ordering = ['-vote_ratio', '-vote_total', 'title']

    # Fixes issue where if user deletes featured image, would break page since not found. 
    @property
    def imageURL(self):
        try:
            # If image doesn't exist, move to next.
            url = self.featured_image.url
        except:
            url = ''
        return url

    @property
    def reviewers(self):
        # Grab all reviewers. Instead of getting queryset of all, it will be list of ids, flat=True converting it into a true list. 
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    # Property decorator allows it to run without (), able to run it as a method. 
    @property
    def getVoteCount(self):
        # Grab all reviews
        reviews = self.review_set.all()
        # Filter to get all upvotes.
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes/totalVotes) * 100

        # Update Project model.
        self.vote_total = totalVotes
        self.vote_ratio = ratio

        self.save()

class Review(models.Model):

    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    # One to many relationship
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        # Creating a list and set two attributes to bind together. This way, no instance of review can have same owner and same project.
        # Prevents someone from leaving multiple reviews for same project. 
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
# Import the user model.
from django.contrib.auth.models import User
import uuid

# Create your models here.
class Profile(models.Model):
    # Creates a 1 to 1 model with the user model, connecting user and profiles. 
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    # Route the profile image to upload into the static/images/profiles folder.
    profile_image = models.ImageField(blank=True, null=True, upload_to='profiles/', default='profiles/user-default.png')
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_x = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        # Ensure this is a string. 
        return str(self.username)
    
    class Meta:
        ordering = ['created']

    @property
    def imageURL(self):
        try:
            # If image doesn't exist, move to next.
            url = self.profile_image.url
        except:
            url = ''
        return url
    
class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        return str(self.name)
    
class Message(models.Model):
    # null=True because people don't need to have an account to send a message, so a sender may not have a profile relationship
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    # Profile model can connect to recipient with related_name="messages", instead of accessing by profiles.messages_set.
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.subject)
    
    # Set the ordering of this model data
    class Meta:
        ordering = ['is_read', '-created']


    
    

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message

class CustomUserCreationForm(UserCreationForm):
    # Specifies metadata about the form, like the model it is based on and what fields should be included
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        # Identifying fields to customize.
        labels = {
            'first_name': 'Name'
        }

    # Loop through and apply a class styling to every field of user creation form
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

        for name, field, in self.fields.items():
            field.widget.attrs.update({'class':'input'})

# ModelForm is a generic model form wheras UserCreationForm is specific for user registration
class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'username', 'location', 'bio', 'short_intro', 'profile_image', 'social_github', 'social_youtube', 'social_x', 'social_linkedin', 'social_website']

    # Loop through and apply a class styling to every field of user creation form
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field, in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        # Want the skill form to be able to access all except modifying the owner
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for name, field, in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for name, field, in self.fields.items():
            field.widget.attrs.update({'class':'input'})

users/templates/users/account.html
{% extends 'main.html' %}

{% block content %}
<!-- Main Section -->
<main class="settingsPage profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i> Edit</a>
            <img class="avatar avatar--xl dev__avatar" src="{{profile.imageURL}}" />
            <h2 class="dev__name">{{profile.name}}</h2>
            <p class="dev__title">{{profile.short_intro}}</p>
            <p class="dev__location">{{profile.location}}</p>

            <ul class="dev__social">
              {% if profile.social_github %}
              <li>
                <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="fa fa-github" style="font-size:36px"></i></a>
              </li>
              {% endif %}

              {% if profile.social_x %}
              <li>
                <a title="X" href="{{profile.social_x}}" target="_blank"><i class="fa fa-twitter" style="font-size:36px"></i></a>
              </li>
              {% endif %}

              {% if profile.social_linkedin %}
              <li>
                <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="fa fa-linkedin-square" style="font-size:36px"></i></a>
              </li>
              {% endif %}

              {% if profile.social_website %}
              <li>
                <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="fa fa-globe" style="font-size:36px"></i></a>
              </li>
              {% endif %}
            </ul>
            
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">{{profile.bio}}</p>
        </div>
        <div class="settings">
          <h3 class="settings__title">Skills</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
        </div>

        <table class="settings__table">
          {% for skill in skills %}
          <tr>
            <td class="settings__tableInfo">
              <h4>{{skill.name}}</h4>
              <p>{{skill.description}}</p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
              <!-- ?next=/account gets added to dynamically set redirect after delete_template shared with others -->
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          {% endfor %}
        </table>

        <div class="settings">
          <h3 class="settings__title">Projects</h3>
          <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>
        </div>

        <table class="settings__table">
          {% for project in projects %}
          <tr>
            <td class="settings__thumbnail">
              <a href="{% url 'project' project.id %}"><img src="{{project.imageURL}}" alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="{% url 'project' project.id %}">{{project.title}}</a>
              <p>{{project.description|slice:"150"}}</p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
    <ul class="messages">

      {% for message in messageRequests %}
      {% if message.is_read == False %}
      <li class="message message--unread">
      {% else %}
      <li class="message">
      {% endif %}

        <a href="{% url 'message' message.id %}">
          <span class="message__author">{{message.name}}</span>
          <span class="message__subject">{{message.subject}}</span>
          <span class="message__date">{{message.created}}</span>
        </a>

      </li>
      {% endfor %}

    </ul>
  </div>
</main>

{% endblock content %}

users/templates/users/login_register.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

{% if page == 'register' %}

<h1>Register</h1>

<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Register an Account</h3>
        <p>Create a new developer account</p>
      </div>

      <form method="POST" action="{% url 'register' %}" class="form auth__form">
      {% csrf_token%}

      {% for field in form %}

        <div class="form_field">
            <label for ="formInput#text">{{field.label}}</label>
                {{field}}
                <!-- If any help text exists, display on page.  -->
                <!-- {% if field.help_text %}
                    <small>{{field.help_text}}</small>
                {% endif %} -->

                {% for error in field.errors %}
                    <p style="color: red">{{error}}</p>
                {% endfor %}

        </div>

      {% endfor %}

        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
        </div>

      </form>
      <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="{% url 'login' %}">Log In</a>
      </div>
    </div>
  </div>

{% else %}

<div class="auth">

    <div class="card">

      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello Developer, Welcome Back!</p>
      </div>

      <form action="" method="POST" class="form auth__form">
        {% csrf_token %}
        
        <!-- Input:User -->
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>

        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="{% url 'reset_password' %}">Forget Password?</a>
        </div>
        
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{% url 'register' %}">Sign Up</a>
      </div>
    </div>
  </div>

{% endif %}

{% endblock content %}

users/templates/users/message.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="messagePage my-xl">
  <div class="content-box">
    <div class="message">
      <a class="backButton" href="{% url 'inbox' %}"><i class="fa fa-arrow-left"></i></a>
      <h2 class="message__subject">{{message.subject}}</h4>
        {% if message.sender %}
        <a href="{% url 'user-profile' message.sender.id %}" class="message__author">{{message.name}}</a>
        {% else %}
        <p class="message__author">{{message.name}}</p>
        {% endif %}
        <p class="message__date">{{message.created}}</p>
        <div class="message__body">{{message.body|linebreaksbr}}</div>
    </div>
  </div>
</main>

{% endblock content %}

users/templates/users/message_form.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'user-profile' recipient.id %}"><i class="fa fa-arrow-left"></i></a>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}

                <!-- If not authenticated, include your email and name when sending message. -->
                {% if request.user.is_authenticated == False %}
                <div class="form__field">
                    <label for="formInput#text">{{form.name.label}}</label>
                    {{form.name}}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{form.email.label}}</label>
                    {{form.email}}
                </div>
                {% endif %}

                <!-- If authenticated, just used your logged in info to send email and name.  -->
                <div class="form__field">
                    <label for="formInput#text">{{form.subject.label}}</label>
                    {{form.subject}}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{form.body.label}}</label>
                    {{form.body}}
                </div>

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

users/templates/users/profile_form.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="fa fa-arrow-left"></i></a>
            <br>

            <form method="POST" action="{% url 'edit-account' %}", enctype="multipart/form-data">
                {% csrf_token %}
            
                {% for field in form %}

                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}
                </div>

                {% endfor %}

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

    <h1>User Profiles</h1>

<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                <h2>FROM AROUND THE WORLD</h2>
            </div>

            <div class="hero-section__search">
                <form id="searchForm" class="form" action="{% url 'profiles' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search Developers </label>
                        <!-- Name becomes the url parameter "search_query" -->
                        <!-- Adding value search_query keeps the most recent search text in the search bar -->
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                        value="{{search_query}}" placeholder="Search by developer name" />
                    </div>
                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">
                {% for profile in profiles %}
                <div class="column card">
                    <div class="dev">
                        <a href="{% url 'user-profile' profile.id%}" class="card__body">
                        <div class="dev__profile">
                            <img class="avatar avatar--md" src="{{profile.imageURL}}" alt="image" />
                            <div class="dev__meta">
                            <h3>{{profile.name}}</h3>
                            <h5>{{profile.short_intro|truncatechars:"50"}}</h5>
                            </div>
                        </div>
                        <p class="dev__info">{{profile.bio|truncatechars:"150"}}</p>
                        <div class="dev__skills">
                            <!-- Query a child set of objects with _set.all -->
                            {% for skill in profile.skill_set.all|slice:"5" %}
                            <span class="tag tag--pill tag--main">
                                <small>{{skill}}</small>
                            </span>
                            {% endfor %}
                        </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

    {% include 'pagination.html' with queryset=profiles custom_range=custom_range %}

</main>

{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.imageURL}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">{{profile.location}}</p>
              <ul class="dev__social">
                
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="fa fa-github" style="font-size:36px"></i></a>
                </li>
                {% endif %}

                {% if profile.social_x %}
                <li>
                  <a title="X" href="{{profile.social_x}}" target="_blank"><i class="fa fa-twitter" style="font-size:36px"></i></a>
                </li>
                {% endif %}

                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="fa fa-linkedin-square" style="font-size:36px"></i></a>
                </li>
                {% endif %}

                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="fa fa-globe" style="font-size:36px"></i></a>
                </li>
                {% endif %}

              </ul>
              {% if request.user.profile.id != profile.id %}
              <a href="{% url 'send-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">{{profile.bio}}</p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
              {% for skill in topSkills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">{{skill.description}}</p>
              </div>
              {% endfor %}

              {% for skill in otherSkills %}
              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill.name}}</small>
                </span>
              </div>
              {% endfor %}
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
            {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id%}" class="project">
                    <img class="project__thumbnail" src="{{project.imageURL}}" alt="project thumbnail" />
                    <div class="card__body">
                      
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{% url 'user-profile' project.owner.id%}">{{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Positive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
            {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}